datasource:
 # default: ${APP_ENV}
  db:
    url: "jdbc:postgresql://dpg-cfus615a499aogr5v740-a.frankfurt-postgres.render.com:5432/page_analyzer_1icr"
    username: "page_analyzer_1icr_user"
    password: "W2fc1nhiHSbcnG4IybaEvrXfUW8L336f"
#  db:
#   username: "postgres"
#    password: "ivan2004"
#    url: "jdbc:postgresql://localhost:5432/JavaProject"
ebean:
  migration:
    run: true