datasource:
  db:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet"
  datasource:
    url: postgresql://postgres:MqWZM8cX3AeyYHfI1N8z@containers-us-west-49.railway.app:7832/railway
    username: "postgres"
    password: "MqWZM8cX3AeyYHfI1N8z"
ebean:
  migration:
    run: true