datasource:
 # default: ${APP_ENV}
  db:
    url: "jdbc:postgresql://dpg-cfut5uda499aogrc88pg-a.frankfurt-postgres.render.com:5432/page_analyzer_4j4y"
    username: "page_analyzer_4j4y_user"
    password: "0NP28F6zLDqWR7vUPKVFezkrujtwCfId"
#  db:
#    username: "postgres"
#    password: "ivan2004"
#    url: "jdbc:postgresql://localhost:5432/JavaProject"
ebean:
  migration:
    run: true