datasource:
  default: ${APP_ENV}
  production:
    url: "jdbc:postgresql://containers-us-west-49.railway.app:7832/postgres"
    username: "postgres"
    password: "MqWZM8cX3AeyYHfI1N8z"
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet1"
ebean:
  migration:
    run: true