datasource:
  default: ${APP_ENV}
  production:
    url: "jdbc:postgresql://containers-us-west-160.railway.app:7900/railway"
    username: "postgres"
    password: "1siU9rHDMPA2NDHaTVWR"
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet1"
ebean:
  migration:
    run: true